### ISSUE TITLE
Is there any special setting for oauth1.0a?

### ISSUE THREAD

**Issue by keyunluo** [nsirons/ibkr_web_client#4]
auth error:

`ibkr_web_client.client - DEBUG - response from live session token: status-code: 401, content: b'{"error":"id: 39687, error: invalid consumer","statusCode":401}'`

**Comment by nsirons** [comment]
Hi, there are no "special settings" required. My initial guess would be that it takes some time for IBKR to activate your API access, especially for paper trading account - please try again :) If things are not working, could you please add more details so I can proceed with investigation ?

**Comment by keyunluo** [comment]
> Hi, there are no "special settings" required. My initial guess would be that it takes some time for IBKR to activate your API access, especially for paper trading account - please try again :) If things are not working, could you please add more details so I can proceed with investigation ?

``` Python
---> 14 client = IBKRHttpClient(config)
     15 client.portfolio_accounts()

File /usr/local/anaconda3/envs/py310/lib/python3.10/site-packages/ibkr_web_client/client.py:42, in IBKRHttpClient.__init__(self, config, logger)
     39 self.session.mount("https://", adapter)
     41 # Initialize brokerage session to get access to trading and market data (/iserver/* endpoints)
---> 42 self.init_brokerage_session()
     43 # The endpoint /iserver/accounts must be called prior to /iserver/marketdata/snapshot
     44 self.get_brokerage_accounts()

File /usr/local/anaconda3/envs/py310/lib/python3.10/site-packages/ibkr_web_client/client.py:54, in IBKRHttpClient.init_brokerage_session(self)
     51 endpoint = "/iserver/auth/ssodh/init"
     52 json_content = {"publish": True, "compete": True}
---> 54 return self.__post(endpoint, json_content)

File /usr/local/anaconda3/envs/py310/lib/python3.10/site-packages/ibkr_web_client/client.py:434, in IBKRHttpClient.__post(self, endpoint, json_content, params)
    431 method = "POST"
    432 url = f"{self.__config.base_url}/{endpoint.lstrip('/')}"
--> 434 headers = self.__authenticator.get_headers(method, url)
    435 self.session.headers.update(headers)
    437 self.__logger.debug(f"{method} request to {url} with params: {params} and json_content: {json_content}")

File /usr/local/anaconda3/envs/py310/lib/python3.10/site-packages/ibkr_web_client/auth.py:22, in IBKRAuthenticator.get_headers(self, method, url)
     21 def get_headers(self, method: str, url: str) -> dict:
---> 22     self.__update_live_session_token()
     23     return self.__generate_standard_headers(method, url)

File /usr/local/anaconda3/envs/py310/lib/python3.10/site-packages/ibkr_web_client/auth.py:38, in IBKRAuthenticator.__update_live_session_token(self)
     36 if fetch_lst:
     37     self.__logger.info("Fetching new live session token")
---> 38     self.__live_session_token, self.__live_session_token_expiration = self.__fetch_live_session_token()
     39     self.__logger.info(
     40         f"New live session token expires at {datetime.datetime.fromtimestamp(self.__live_session_token_expiration/1000)}"
     41     )

File /usr/local/anaconda3/envs/py310/lib/python3.10/site-packages/ibkr_web_client/auth.py:142, in IBKRAuthenticator.__fetch_live_session_token(self)
    138     self.__logger.error("ERROR: Request to /live_session_token failed. Exiting...")
    139     self.__logger.debug(
    140         f"response from live session token: status-code: {lst_response.status_code}, content: {lst_response.content}"
    141     )
--> 142     raise SystemExit(0)  # TODO <- maybe add retry mechanism
    143 self.__logger.info("Successfully received live session token response")
    145 response_data = lst_response.json()

SystemExit: 0
```

Python3.12 and Pyhton3.10 are all not working  for me, and the account type is live trading account.

**Comment by nsirons** [comment]
I don't think it is related to python version or package dependencies, most likely there is something wrong with your configuration of oath. I can replicate same error if I use incorrect Consumer Key (like some random characters). 

Please make sure that you have correctly set settings in https://www.interactivebrokers.com/oauth/#/configuration , and that ouath is enabled. Double check that Consumer key follows all rules (should have 9 letters, contain no numbers, contain no special characters), check with `echo $API_IBKR_CONSUMER_KEY` that returned value is the same as in config settings.

**Comment by keyunluo** [comment]
> I don't think it is related to python version or package dependencies, most likely there is something wrong with your configuration of oath. I can replicate same error if I use incorrect Consumer Key (like some random characters).
> 
> Please make sure that you have correctly set settings in https://www.interactivebrokers.com/oauth/#/configuration , and that ouath is enabled. Double check that Consumer key follows all rules (should have 9 letters, contain no numbers, contain no special characters), check with `echo $API_IBKR_CONSUMER_KEY` that returned value is the same as in config settings.

The fact that I hardcoded parameters like token_secret, consumer_key into the code didn't help.

I also searched for related issues on Google, and it seems that this is a common phenomenon:
https://stackoverflow.com/questions/79281170/interactive-brokers-oauth1-live-session-token

I would like to ask, do I need to open the cpweb gateway first? Now I am accessing it directly.

**Comment by nsirons** [comment]
The whole point of the package is not to use any gateway.

Please try to repeat registration process again (creating with new consumer key, dhparams, secret tokens etc..)

**Comment by keyunluo** [comment]
> The whole point of the package is not to use any gateway.
> 
> Please try to repeat registration process again (creating with new consumer key, dhparams, secret tokens etc..)


Now it's Ok, IB does take several days to activate，Thanks!
